In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
v= np.zeros((10, 10))

In [10]:
print(v.size, v.itemsize)

100 8


In [11]:
print("array size in bytes : ",v.size * v.itemsize)  # array'in toplam eleman büyüklüğünü byte olarak bulmak için

array size in bytes :  800


In [12]:
nz = np.nonzero([1,2,0,0,4,0])  # değeri 0 olmayan arraylerin index numaralarını bulmak için
print(nz)

(array([0, 1, 4], dtype=int64),)


In [15]:
x = np.array([1,2,0,0,4,0])
np.where(x != 0)  # where fonksiyonu ile de değeri 0 olmayan elemanların indexlerini bulabilriz.

(array([0, 1, 4], dtype=int64),)

In [167]:
nz2 = np.array([[1,2,5],[6,4,0]])  # iki boyutlu arraylerde 0 olmayan elemanların indexlerini bulma
print(nz2)
np.nonzero(nz2)  # axis=0 ve axis=1 index değerlerini ayrı ayrı array object olarak döndürüyor.

[[1 2 5]
 [6 4 0]]


(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [28]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(99,(6,7,8)))  # array'in 100. sıradaki elemanının 3 boyutlu indexini verir

(1, 5, 3)


In [26]:
# How to get the documentation of the numpy add function from the command line?

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [23]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [30]:
# Create a null vector of size 10 but the fifth value which is 1

z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [35]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
y = 1 + np.arange(4)  # array([1, 2, 3, 4]) oluşturmak için veya np.range(1,5) ile de yapılabilir.
z = np.diag(y, k=-1)  # k diagonal numarası: 0 ise tam ortası +1 ise bir üstü, -1 ise bir altı
z  # matris içine yerleştirilen arrayin boyutuna göre yeni matrisin boyutunu değiştiriyor.

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [169]:
y = np.arange(1,5)
z = np.diag(y, k=-1)   # k is diagonal index, default value is 0.
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [170]:
# Create a vector with values ranging from 10 to 49

arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [38]:
# Create a vector with values ranging from 10 to 49

arr6 = arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [173]:
np.concatenate((arr[1:-1], arr[0:1]))

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 10])

In [174]:
np.concatenate(arr[::-1][0:1], np.concatenate((arr[1:-1], arr[0:1])))

TypeError: only integer scalar arrays can be converted to a scalar index

In [54]:
# Create a 8x8 matrix and fill it with a checkerboard pattern

arr2 = np.zeros((8,8), dtype=int)
arr2[::2,1::2] = 1
arr2[1::2,::2] = 1
arr2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [55]:
# Create a 3x3 identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:

np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [57]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
np.identity(8,7)  # identity fonksiyonuna ikinci bir boyut girilemez. Hata verir.

TypeError: Cannot interpret '7' as a data type

In [59]:
# Create a 3x3x3 array with random values

np.random.rand(3,3,3)

array([[[0.49232912, 0.57966224, 0.23296543],
        [0.45342591, 0.1576387 , 0.51464565],
        [0.75268111, 0.94133822, 0.95067389]],

       [[0.52897566, 0.78241066, 0.87699811],
        [0.63411337, 0.71649349, 0.73109641],
        [0.58038759, 0.33858449, 0.06463024]],

       [[0.34168663, 0.76203866, 0.16917316],
        [0.69434016, 0.88426378, 0.047847  ],
        [0.05163455, 0.40487612, 0.62640066]]])

In [60]:
np.random.random((3,3,3))

array([[[0.51036195, 0.34304634, 0.46708581],
        [0.12726525, 0.23197687, 0.51115308],
        [0.2273209 , 0.33340195, 0.99292734]],

       [[0.55491528, 0.59821133, 0.78860015],
        [0.38809597, 0.49753455, 0.24558872],
        [0.36567927, 0.24478119, 0.41007658]],

       [[0.45210681, 0.30741451, 0.83719329],
        [0.52430864, 0.22296901, 0.96417652],
        [0.01988042, 0.76408627, 0.4209783 ]]])

In [65]:
# Create a checkerboard 8x8 matrix using the tile function

np.array([[0,1],[1,0]])  # tekrar edilecek pattern

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))  # tile fonksiyonu içerisine pattern ile kaç kez tekrar edileceği girilmelidir.

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
# Create a 10x10 array with random values and find the minimum and maximum values

arr3 = np.random.randint(5, 50, (10,10))

arr3.min()
np.argmin(arr3)

5

In [68]:
arr3.max()

49

In [75]:
arr3

array([[47, 41,  7, 10,  9,  5, 12, 35, 42, 18],
       [17, 14, 23, 18,  7, 30, 15, 35, 14, 35],
       [12, 21,  5, 18, 37,  5, 45, 25,  7, 15],
       [38, 16, 29, 37, 19, 28, 33, 42, 27, 37],
       [32, 28, 37,  9, 28, 33, 49, 31, 28, 38],
       [ 6, 33, 15, 19, 33, 23, 33, 11, 10, 41],
       [13, 26,  6, 14, 26, 28, 31,  5,  5, 24],
       [17, 19, 38,  6, 14, 34, 21, 20, 27, 23],
       [27, 11, 40, 28, 47, 18, 25, 20, 33, 39],
       [27, 32,  5, 19, 47, 16, 46, 44, 48, 32]])

In [76]:
np.unravel_index(np.argmin(arr3),(10,10))   # argmin değerinin position ını bulmak için

(0, 5)

In [80]:
np.where(arr3==20)

(array([7, 8], dtype=int64), array([7, 7], dtype=int64))

In [81]:
np.unravel_index(arr3.max(),(10,10))   # max. değerin positionını bulmak için

(4, 9)

In [83]:
np.unravel_index(np.where(arr.reshape(-1)==14)[0][1],(10,10))

IndexError: index 1 is out of bounds for axis 0 with size 1

In [85]:
# Create a random vector of size 30 and find the mean value

s = np.random.randint(1,100,30)
s

array([75, 32, 95, 98, 63, 54,  1, 24, 24, 99, 93, 60, 26, 75, 31, 84, 75,
       56,  7,  2,  4, 31, 74, 42, 46, 65, 36, 47, 33, 93])

In [86]:
s.mean()

51.5

In [88]:
# Normalize a 5x5 random matrix

s = np.random.randint(1,100,(5,5))
s, s.mean(), s.std()

(array([[83, 56, 38, 86, 62],
        [53, 99, 21, 85, 34],
        [89, 17, 75,  7, 65],
        [60, 41,  2, 13, 24],
        [52, 31, 76, 50,  3]]),
 48.88,
 28.634692245596074)

In [89]:
Z = (s - s.mean()) / (s.std())
print(Z)

[[ 1.19156161  0.24864943 -0.37995868  1.29632963  0.45818547]
 [ 0.14388141  1.75032438 -0.97364413  1.26140696 -0.51964938]
 [ 1.40109765 -1.11333482  0.91218022 -1.46256155  0.56295349]
 [ 0.38834013 -0.27519066 -1.63717492 -1.25302552 -0.86887611]
 [ 0.10895874 -0.6244174   0.9471029   0.03911339 -1.60225225]]


In [90]:
# Create a 2d array with 1 on the border and 0 inside

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [92]:
# What is the result of the following expression? 

print(0 * np.nan)
print(np.nan == np.nan)  # nan float değer aldığı için nan == nan False verir.
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
np.nan

nan
False
False
nan
True
False


nan

In [98]:
(1/10)*3

0.30000000000000004

In [97]:
(1/10)*3  == 0.3

False

In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

In [121]:
# What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))  # numpy import ettikten sonra sum fonksiyonu farklı şekilde çalışıyor.

# İçine yazdığınız array like verinin belirtilen index üzerinden toplamını veriyor.

9
10


0.30000000000000004

In [100]:
# Create a 3x3 matrix with values ranging from 0 to 8 

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
np.random.randint(0,9,(3,3))

array([[3, 2, 6],
       [1, 8, 8],
       [0, 3, 7]])

In [109]:
# How to add a border (filled with 0's) around an existing array?

arr4 = np.zeros((7,7))
arr4[1:-1, 1:-1] = 1
arr4[3,3]=9
arr4

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 9., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [120]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, constant_values=5)
print(Z)

[[5. 5. 5. 5. 5. 5. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 5. 5. 5. 5. 5. 5.]]


In [127]:
# What are the result of the following expressions?

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\user\AppData\Local\Temp/ipykernel_14432/2610099716.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp/ipykernel_14432/2610099716.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [122]:
np.array(0)

array(0)

In [ ]:
type(np.array(0))

In [123]:
np.array(0) + np.array(5)

5

In [124]:
type(np.array(0) + np.array(5))

numpy.int32

In [ ]:
type(np.array(0))

In [125]:
print(np.array(0) / np.array(0))

nan


C:\Users\user\AppData\Local\Temp/ipykernel_14432/4120864939.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


In [126]:
print(np.array(0) // np.array(0))

0


C:\Users\user\AppData\Local\Temp/ipykernel_14432/4108562882.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [131]:
# How to round away from zero a float array ?

arr5 = np.random.uniform(-10,+10,15)
print(arr5)

[ 6.27287646 -1.02643961  4.56975221  2.05748616  4.18163898 -2.09729602
 -0.86436898  0.48549024 -0.19798461  4.62387734 -2.72767722  9.90149374
  0.52421915 -2.55101562 -4.66620275]


In [132]:
np.abs(arr5)

array([6.27287646, 1.02643961, 4.56975221, 2.05748616, 4.18163898,
       2.09729602, 0.86436898, 0.48549024, 0.19798461, 4.62387734,
       2.72767722, 9.90149374, 0.52421915, 2.55101562, 4.66620275])

In [138]:
np.ceil(np.abs(arr5))

array([ 7.,  2.,  5.,  3.,  5.,  3.,  1.,  1.,  1.,  5.,  3., 10.,  1.,
        3.,  5.])

In [139]:
print (np.copysign(np.ceil(np.abs(arr5)), arr5))

[ 7. -2.  5.  3.  5. -3. -1.  1. -1.  5. -3. 10.  1. -3. -5.]


In [ ]:
# Consider an integer vector Z, which of these expressions are legal?

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [133]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## The operators << and >> are bit shift operators (left and right, respectively). In your particular example (with << ), you are performing x = x * 2^z for each array element, resulting in your modified output. The operator >> in the same example would yield an output characterized by x = x / 2^z for each array element.

In [142]:
Z**Z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [143]:
2 << Z

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [144]:
Z >> 2

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2], dtype=int32)

In [146]:
Z <- Z  # Z < (-Z) ile aynı

array([False, False, False, False, False, False, False, False, False,
       False])

In [147]:
1j*Z  3 array değerlerini kompleks sayıya dönüştürdü.

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [151]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [152]:
Z<Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [153]:
Z>Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [154]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [156]:
# How to find common values between two arrays? 

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)


[8 7 7 9 8 6 2 9 8 7]
[0 8 5 5 4 1 3 4 9 6]
[6 8 9]


In [160]:
print(np.intersect1d(Z1,Z2, assume_unique=False ,return_indices=True))

(array([6, 8, 9]), array([5, 0, 3], dtype=int64), array([9, 1, 8], dtype=int64))


In [163]:
print(np.intersect1d(Z1,Z1.max(), assume_unique=False ,return_indices=True))

(array([9]), array([3], dtype=int64), array([0], dtype=int64))


In [164]:
#  Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


C:\Users\user\AppData\Local\Temp/ipykernel_14432/3327402174.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [179]:
arr7= np.random.randint(0,17, (4,4,2))
arr7

array([[[16,  3],
        [12,  5],
        [ 5, 14],
        [ 3, 15]],

       [[15,  3],
        [ 0, 11],
        [ 7,  1],
        [ 8, 15]],

       [[13, 10],
        [ 4,  4],
        [ 8,  8],
        [15,  1]],

       [[13,  9],
        [ 4,  3],
        [ 4, 13],
        [ 0, 16]]])

In [180]:
arr7.ndim

3

In [181]:
arr7.shape

(4, 4, 2)

In [182]:
arr7.size

32

In [183]:
arr7.dtype

dtype('int32')

In [184]:
arr7.itemsize  # byte

4

In [185]:
arr7.dtype.itemsize

4

In [187]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [188]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [190]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1, 5, 8, 9, 4])

np.split(x, 3)

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1]), array([5, 8, 9, 4])]

In [193]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1, 5, 8, 9, 4,2])

np.split(x, [3, 6, 9])

[array([1, 2, 3]), array([99, 99,  3]), array([2, 1, 5]), array([8, 9, 4, 2])]

In [198]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1, 5, 8, 9, 4,2])

xx = np.sort(x)

In [199]:
xx

array([ 1,  1,  2,  2,  2,  3,  3,  4,  5,  8,  9, 99, 99])

In [200]:
sorted(x)  # liste olarak geri döndürür.

[1, 1, 2, 2, 2, 3, 3, 4, 5, 8, 9, 99, 99]

In [207]:
np.random.seed(22)
x = np.random.randint(0,9, (3,3))
y = np.random.randint(0,9, (3,3))
print(x)
print(y)

[[5 4 0]
 [4 6 6]
 [4 8 4]]
[[2 8 7]
 [2 8 8]
 [5 4 2]]


In [205]:
x + y 

array([[ 7, 12,  7],
       [ 6, 14, 14],
       [ 9, 12,  6]])

In [208]:
x + 5

array([[10,  9,  5],
       [ 9, 11, 11],
       [ 9, 13,  9]])

In [209]:
x - y

array([[ 3, -4, -7],
       [ 2, -2, -2],
       [-1,  4,  2]])

In [210]:
y -3

array([[-1,  5,  4],
       [-1,  5,  5],
       [ 2,  1, -1]])

In [211]:
x/y

array([[2.5 , 0.5 , 0.  ],
       [2.  , 0.75, 0.75],
       [0.8 , 2.  , 2.  ]])

In [214]:
x % 3

array([[2, 1, 0],
       [1, 0, 0],
       [1, 2, 1]], dtype=int32)

In [215]:
x * y

array([[10, 32,  0],
       [ 8, 48, 48],
       [20, 32,  8]])

In [216]:
x * 6

array([[30, 24,  0],
       [24, 36, 36],
       [24, 48, 24]])

In [217]:
np.sqrt(x)

array([[2.23606798, 2.        , 0.        ],
       [2.        , 2.44948974, 2.44948974],
       [2.        , 2.82842712, 2.        ]])

In [218]:
np.sqrt(y)

array([[1.41421356, 2.82842712, 2.64575131],
       [1.41421356, 2.82842712, 2.82842712],
       [2.23606798, 2.        , 1.41421356]])

In [219]:
np.exp(x)

array([[1.48413159e+02, 5.45981500e+01, 1.00000000e+00],
       [5.45981500e+01, 4.03428793e+02, 4.03428793e+02],
       [5.45981500e+01, 2.98095799e+03, 5.45981500e+01]])

In [222]:
x.min() , y.min()

(0, 2)

In [221]:
x , y

(array([[5, 4, 0],
        [4, 6, 6],
        [4, 8, 4]]),
 array([[2, 8, 7],
        [2, 8, 8],
        [5, 4, 2]]))

In [224]:
x.max(), y.max()

(8, 8)

In [226]:
x.max(axis=0), x.max(axis=1)

(array([5, 8, 6]), array([5, 6, 8]))

In [228]:
y.min(axis=0), y.min(axis=1)

(array([2, 4, 2]), array([2, 2, 2]))

In [232]:
x.mean(), x.mean(axis=0), x.mean(axis=1)

(4.555555555555555,
 array([4.33333333, 6.        , 3.33333333]),
 array([3.        , 5.33333333, 5.33333333]))

In [235]:
np.median(y), np.median(y, axis=0), np.median(y, axis=1) 

(5.0, array([2., 8., 7.]), array([7., 8., 4.]))

In [238]:
x.std(), x.std(axis=0), x.std(axis=1)

(2.0608041101101566,
 array([0.47140452, 1.63299316, 2.49443826]),
 array([2.1602469 , 0.94280904, 1.88561808]))

In [244]:
x, y

(array([[5, 4, 0],
        [4, 6, 6],
        [4, 8, 4]]),
 array([[2, 8, 7],
        [2, 8, 8],
        [5, 4, 2]]))

In [243]:
np.mod(x, y)  # to find modulus(remainder) of each element of x array according to y array. 

array([[1, 4, 0],
       [0, 6, 6],
       [4, 0, 0]], dtype=int32)

In [245]:
np.remainder(x, y)  # to find modulus(remainder) of each element of x array according to y array. 

array([[1, 4, 0],
       [0, 6, 6],
       [4, 0, 0]], dtype=int32)

In [246]:
np.sin(x)  # To find sinus of each elemnets of array

array([[-0.95892427, -0.7568025 ,  0.        ],
       [-0.7568025 , -0.2794155 , -0.2794155 ],
       [-0.7568025 ,  0.98935825, -0.7568025 ]])