## Creation of Numpy Array

In [71]:
import numpy as np  # numpy modülünü np adıyla import ettik.

In [3]:
# numpy array oluşturmanın en uygun yolu bir python listesini dönüştürmektir. Ör:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)  # Bu şekilde bir listeyi numpy array e dönüştürebilirsiniz.

array([1, 2, 3])

In [6]:
mylist  # listemi kontrol ettiğimde halen liste olduğunu görebilirim.

[1, 2, 3]

In [9]:
# numpy array'i bir değişkene atarsak ve türünü kontrol edersek:
myarr = np.array(mylist)
myarr
type(myarr)  3 bir numpy array olduğunu görebiliriz.

numpy.ndarray

In [ ]:
# Yukarıdaki örnek tek elemanlı bir vektör haline dönüştü.

In [ ]:
# Şimdi de iki boyutlu bir array yapalım. Bunun için öncelikle içiçe listelerden oluşan bir liste tanımlayalım.

In [10]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# şimdi de bu listemizi bir numpy arraye dönüştürelim.
np.array(my_matrix)  # Görüldüğü gibi 3 satır ve 3 sütundan oluşan 2 boyutlu bir matrix oluştu.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# numpy ile kullanılabilecek built-in fonksiyonlara bakalım:

# np.arange(start, stop, step)  # bu fonksiyon pythondaki range fonksiyonu ile aynı işlemi yapmaktadır.

In [12]:
np.arange(0,10)  # 0'dan başlayarak 10' a kadar olan sayıları içeren bir numpy array oluşturdu.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)  # 0'dan başlayıp 2'şer artarak 10'a kadar giden bir array oluşturduk

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,101,20)  # 0 ' dan başlayarak 100'e kadar giden ve 20'şer artan bir array(dizi) oluşturduk.

array([  0,  20,  40,  60,  80, 100])

In [ ]:
# Gerçek veri setleri ile çalışırken 1'lerden veya 0'lardan oluşan çok elemanlı sayı dizileri oluşturmak gerekebilir.
# Bunun için aşağıdaki yöntem kullanılır.

In [18]:
np.zeros(5)  # Bu fonksiyon parantez içerisine yazdığınız sayıda tek boyutlu float 0'lardan oluşan bir vektör oluşturur.
# Parantez içerisinde belirtilmediği sürece float veri üretir. 

array([0., 0., 0., 0., 0.])

In [20]:
# İki boyutlu 0'lardan oluşan bir array oluşturmak istiyorsak parantez içerisine TUPLE olarak her bir boyutun sayısı yazılır.
# Ör:
np.zeros((5,5))  # 5 satır ve 5 sütundan oluşan toplamda 25 elemanlı 0 dizisi oluşturur.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
# şimdi de 2 satır ve 5 sütundan oluşan 2 boyutlu bir dizi oluşturalım.
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((4,4))  # Benzer şekilde bu fonksiyon ile de elemanları 1 olan 4 satır ve 4 sütundan oluşan bir sayı dizisi oluşturabiliriz.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# array oluşturmanın bir diğer yolu da
# np.linspace(start, stop, number of numbers included) fonksiyonunu kullanmaktır.
# Burada dizide yer alacak sayıların başlangıç, bitiş değerleri ve dizide yer alacak sayı sayısı belirtilmelidir.
# Bu şekilde oluşturulan sayı dizisinde sayılar eşit aralıklarla oluşturulur.
# Ör:

In [28]:
np.linspace(0,10,3) # 1'den 10'a kadar(10 dahil) sayılardan oluşacak ve toplamda 3 sayı yer alacak bir sayı dizisi oluşturalım.
# Görüldüğü gibi EŞİT ARALIKLARLA BELİRLENMİŞ 3 sayıdan oluşan bir sayı dizisi oluşturuldu. 

array([ 0.,  5., 10.])

In [30]:
# Aynı şekilde 0'dan başlayıp 10 dahil sayılardan oluşan ve 11 sayı içeren bir array oluşturalım.
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [32]:
len(np.linspace(0, 5, 21))  # Bu dizinin uzunluğunu kontrol ettiğimizde 21 eleman içerdiğini görebiliriz.

21

In [33]:
# Son olarak da array oluşturmak için np.eye() fonksiyonunu kullanabilirsiniz.
# Bu bir identity matrix oluşturmak için ve genellikle lineer cebir işlemlerinde kullanılır.
# Ör:
np.eye(5)  # parantez içerisine yazdığınız tek rakam ile iki boyutlu bir identity matrix oluşturabilirsiniz.
# Aşağıda görüldüğü gibi 5 satır ve 5 sütundan oluşan bir identity matrix oluştu.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# Rastgele(Random) olarak array oluşturmak için kullanılabilecek fonksiyonlara bakalım:
# np.random.rand()  # Bu fonksiyon belirtilen şekilde(boyutta) random olarak oluşturulan sayılar içeren array oluşturur.
# Oluşturulan array deki her bir sayı 0-1 arasında (0 dahil, 1 dahil değil) float sayılardır.

np.random.rand(1)  # Bu fonksiyonu her çalıştırdığınızda her seferinde farklı bir sayı ürettiğini görebilirsiniz.


array([0.05748568])

In [36]:
np.random.rand(5,6)  # iki boyutlu bir rastgele sayı dizisi oluşturmak için yukarıdakinden farklı 
# olarak boyut sayıları doğrudan parantez içine yazılır.

array([[0.84889788, 0.02609066, 0.24328188, 0.766619  , 0.01836225,
        0.62011927],
       [0.93853294, 0.52148003, 0.42707228, 0.99138409, 0.03011161,
        0.52382258],
       [0.22932675, 0.64851995, 0.0409178 , 0.8627272 , 0.94162627,
        0.38206284],
       [0.9919543 , 0.87848857, 0.75401375, 0.4820976 , 0.1547341 ,
        0.17616026],
       [0.72938912, 0.75894688, 0.07539291, 0.76983603, 0.63108311,
        0.59558787]])

In [37]:
np.random.rand(5,2)

array([[0.40938889, 0.60978896],
       [0.88300776, 0.36112187],
       [0.55657679, 0.8207976 ],
       [0.1934366 , 0.96544949],
       [0.81349323, 0.5266032 ]])

In [ ]:
# Standart normal dağılımlı(standart normal distribution) bir array oluşturmak için 
# np.random.randn() fonksiyonu kullanılır.
# Standart normal dağılım normal dağılım kullanılarak yapılan olasılık hesabının zor olduğu durumlarda kullanılır.
# Normal dağılımın ortalaması 0' a, varyansı da 1'e eşitlenerek olasılık işlemleri yapılabilir. Bu işlem için kullanılan
# yönteme standart normal dağılım denir.
# Bu yöntemle negatif sayılar da dizide yer alabilir.

## Normal dağılımı kullanarak bazı olasılık değerlerini elde etmek çok zor ve zahmetli bir iştir.[1] [2][3] Bu yüzden elde edilen normal dağılımın ortalaması 0 a ve varyansı da 1 e eşitlenerek daha kolay işlem yapılması sağlanabilir.[4] Bu işlem için kullanılan yönteme ise standart normal dağılım denir.

In [38]:
np.random.randn(10)  # standart normal dağılımlı 10 elemandan oluşan bir array oluşturduk.

array([-0.89114627, -0.71497382,  1.32318309,  1.67826494, -0.82984954,
       -0.50482557,  1.12832352, -1.15789404,  1.04981776,  0.61319146])

In [39]:
# Aynı şekilde 2 boyutlu bir array de oluşturulabilir.
np.random.randn(2,3)  # 2 satır ve 3 sütundan oluşan standart normal dağılımlı bir array oluşturduk. 

array([[ 2.1128911 ,  0.48044121, -0.55559057],
       [-0.04587215, -0.04064256,  0.97852335]])

In [ ]:
# Random integer sayılar içeren array oluşturmak için;
# np.random.randint() fonksiyonu kullanılır.

In [42]:
# Ör:

np.random.randint(0, 101, 5)  # 0 ile bir arasındaki sayılardan rastgele seçilerek 5 elemanlı bir array oluşturduk.

array([ 0, 82, 19, 31, 84])

In [43]:
# Aynı şekilde iki boyutlu int sayılardan oluşan bir array oluşturmak için:

np.random.randint(0, 101, (4,5))  # 4 satır ve 5 sütundan oluşan ve 0-101 arasındaki sayıları içeren bir array oluşturduk.

array([[44, 74, 62,  7, 42],
       [64, 81, 20, 94,  9],
       [54, 63, 89, 91, 59],
       [54, 68, 72, 31, 91]])

In [44]:
# Random olarak ürettiğiniz bir serinin aynı sayıları içerecek şekilde tekrar üretilmesini istiyorsanız
# np.random.seed(arbitrary number) fonksiyonunu kullanırsınız. Ör:

np.random.seed(42)   # seed modülünü rastgele bir sayı ile aktif hale getirdikten sonra
# aynı hücrede array oluşturma işlemini yapmalısınız.

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
np.random.rand(4)  # seed işlemini yapmadan çalıştırdığımızda farklı sayıları içeren bir seri üretmiş olduk.

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [47]:
np.random.seed(42)  # seed içerisinde kullanılan abritrary number ile aynı şekilde seri oluşturduğunuzda 
# çıktının aynı olduğunu görebilirsiniz.

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [48]:
# Eğer seed içerisine başka bir sayı yazarsanız bu sefer farklı sayıları içeren bir seri elde edersiniz.
# Ör:

np.random.seed(48)
np.random.rand(5)

array([0.01749027, 0.89157327, 0.28486117, 0.29897638, 0.79203426])

In [49]:
# 48 arbitrary sayısı ile aynı şekilde tekrar bir seri olulturduğumuzda çıktıdaki değerlerin de aynı olduğunu görebiliriz.

np.random.seed(48)
np.random.rand(5)

array([0.01749027, 0.89157327, 0.28486117, 0.29897638, 0.79203426])

In [51]:
# Oluşturduğumuz bir array'i bir değişkene atayarak bazı işlemler yapabiliriz.
# Ör: 

arr = np.arange(0,25)  # Burada 0-25 arasında sayılardan oluşan tek boyutlu bir array oluşturarat arr değişkenine atadık.

In [52]:
# reshape özelliği ile bir array in boyutunu değiştirebilirsiniz.
# burada dikkat edilmesi gereken husus tek boyutlu array deki eleman sayısı ile farklı boyutlara dönüştürüldüğündeki 
# eleman sayısı aynı olmalı ve ona göre boyut belirlenmelidir.

arr.reshape(5,5)  # Burada da arr değişkenini 5 x 5 lik iki boyutlu bir array e dönüştürdük.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
# bir array ürettikten sonra o array deki max, min değerleri ve bunların index numaralarını bulmak için 
# aşağıdaki işlemleri yapabilirsiniz.

ranarr = np.random.randint(1, 101, 10)

In [54]:
ranarr

array([93, 81, 30,  7, 87, 32, 47, 49, 92, 29])

In [55]:
ranarr.max()  # array deki max değeri bulmak için

93

In [56]:
ranarr.min()  # array deki min değeri bulmak için

7

In [58]:
ranarr.argmax()  # array deki max değerin İNDEX değerini bulmak için

0

In [59]:
ranarr.argmin()  # array deki min değerin İNDEX değerini bulmak için

3

In [60]:
ranarr.dtype  # array deki data type larını bulmak için

dtype('int32')

In [61]:
arr  # Yukarıda ürettiğimiz array üzerinden array in boyutlarını nasıl kontrol ettiğimize bakalım.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
# Eğer bunun shape ini kontrol ettiğimde 

arr.shape  # komutunu kullanırım

# sonuçta 25 elemandan oluşan tek boyutlu bir array olduğu sonucunu görürüm.

(25,)

In [64]:
arr = arr.reshape(5, 5)  # Bu array i 5 x 5 lik iki boyutlu bir array'e dönüştürerek yeniden arr değişkenine atarsak;

# ve shape ini kontrol edersek

arr.shape  # sonuçta 5 satır ve 5 sütundan oluşan iki boyutlu bir array olduğunu görürüz.

(5, 5)

In [65]:
# bu array i 25 x 1 lik bir array e dönüştürürsek 25 satır ve bir sütundan oluşan ve 
# her bir elemanı köşeli parantez içinde yer alan bir array elde ederiz.

arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [66]:
# Aynı array'i 1 x 25 lik bir array e dönüştürürsek tek satırlık 25 elemanlı aşağıdaki arrayi elde ederiz.
# Burada köşeli parantez içinde yeni bir köşeli parantez olduğuna dikkat edelim.

arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [68]:
arr.reshape(25,)  # Bu şekilde de orjinal haline dönüştürmüş oluruz.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
myarray = np.linspace(0, 10, 101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

# Numpy Array Indexing and Selection

In [ ]:
# Tek boyutlu arraylerde indeksleme ve slicelama python listelerindekine benzerdir.


In [73]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[8]

8

In [75]:
arr[1:5]

array([1, 2, 3, 4])

In [77]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [81]:
arr[:5]

array([0, 1, 2, 3, 4])

In [82]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [83]:
# Python listelerinden farklı olarak arraylerde arraylerin belirli bir kısmının veya tamamının değerini
# yeni bir değer atayarak değiştirebilirsiniz.
# Ör:

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr[0:5] = 100  # arrayin 0-5. indexleri arasındaki elemanların değerini 100 yaptık.

In [85]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [88]:
arr = np.arange(0,11)  # arrayimizi yeniden oluşturalım.

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
slice_of_arr = arr[0:5]  # arrayin belirli bir bölümünü yeni bir değişkene atadık.

In [92]:
slice_of_arr  # yeni değişkenin çıktısını aldığımızda array in atadığımız kısmından oluştuğunu görürüz.

array([0, 1, 2, 3, 4])

In [95]:
slice_of_arr[:] = 99  # bu değişkenimizin taşıdığı değerlerin tamamını 99 yaptık.

In [96]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [97]:
# Yukarıdaki işlemlerden sonra orjinal array'de nasıl bir değişiklik olduğuna bakalım.

arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# Yukarıdaki slicelama ve yeni değişkene atama işleminden sonra yapılan yeni değer atama sonucunda orjinal arrayin
# değerlerinin de etkilendiğini ve değiştiğini gördük.

In [98]:
# Eğer orjinal arrayimizin değişmesini istemiyorsak arrayimizi kopyalamalıyız.
# Ör:

arr_copy = arr.copy()  # işlemi ile orjinal arrayin bir kopyasını oluşturduk.

In [99]:
arr_copy[:] = 100  # arrayimizin kopyasının tüm elemanlarını 100 yaptık. 

In [100]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [101]:
arr  # arrayimizin kopyasında yaptığımız değişikliklerden orjinal arrayin etkilenmediğini ve
# bunun copy ile oluşturulan kopyadan kaynaklandığını gördük.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# iki boyutlu arraylerde indexleme ve koşullu seçim

In [103]:
arr_2d = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])

In [104]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [105]:
arr_2d.shape

(3, 3)

In [106]:
arr_2d[0]  # 0.  satırdeki elemanları getirir.

array([ 5, 10, 15])

In [107]:
arr_2d[2]  # 2. satırdaki elemanları getirir.

array([35, 40, 45])

In [108]:
arr_2d[0][1]  # 0. satırın 1. sütunundaki elemanı getirir.

10

In [109]:
arr_2d[0, 1]  # Bu da aynı şekilde 0. satırın 1. sütunundaki elemanı getirir.

10

In [110]:
arr_2d[:2, 1:]  # 0-2. satırlar arasındaki ile 1. sütüundan sonraki elemanları getirmek için bu şekilde slicelama yapılır.

array([[10, 15],
       [25, 30]])

In [113]:
# Şimdi de koşullu seçim nasıl yaapılır konusuna bakalım:

arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr > 4  # arrayde değeri 4'den büyük elemanlar için aşağıdaki boolean çıktıyı üretir.

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [119]:
bool_arr = arr > 4  # Bu işlemin sonucunu bir değişkene atayıp aşağıdaki gibi array işlemlerinde kullanabilirim.


In [120]:
arr[bool_arr]  # arrayimizin bool_arr koşuluna uyan tüm elemanlarını slice ladık.

array([ 5,  6,  7,  8,  9, 10])

In [121]:
# Yukarıdaki koşullu işlemleri daha kısa bir şekilde şöyle yaparız.
# Çoğunlukla da bu yöntem kullanılır.:

arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [123]:
len(arr[arr>4])  # array in eleman sayısını bulmak için

6

# Numpy Operations

In [124]:
import numpy as np   # Önce numpy modülünü import edelim.

In [126]:
arr = np.arange(0,10)  # Klsaik arrayimizi oluşturalım.

In [127]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
arr + 5  # arr ile 5 'i toplama işlemini yaptığımızda arrayin tüm elemanlarına 5 eklendiğini görürüz.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [129]:
arr -2  # benzer şekilde arr den 2'yi çıkardığımızda array'in tüm elemanlarından 2'nin çıkarıldığını görebiliriz.

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [130]:
arr + arr  # arrayi kendisi ile topladığımızda ise aşağıdaki sonuç elde edilir.
# Bu işlemin yapılabilmesi için iki arrayin de aynı uzunlukta olması gerekir.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [131]:
arr * arr  # benzer şekilde arrayi kendisi ile de çarpabiliriz.

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [132]:
arr - arr  # bir array den bir arrayi çıkartabiliriz.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [134]:
arr / arr  # bir arrayi başka bir array'e bölebiliriz.

# Ancak arrayin elemanlarından biri 0 ise bir sayının sıfıra bölünmesi durumunda Runtime Warning uyarısı gelir.
# Ve sıfıra bölünen sayı yerine "nan" ifadesi yazılır.

C:\Users\user\AppData\Local\Temp/ipykernel_3720/1643453781.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr  # bir arrayi başka bir array'e bölebiliriz.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [135]:
1 / 0  # Normal python da 1!i sıfıra bölmek istediğimizde hata alırız.

ZeroDivisionError: division by zero

In [136]:
# Benzer şeyi numpy ile yaparsak

1 / arr  # 1'i arrayin elemanlarına bölersek, hata değil uyarı alırız ve
# arrayin elemanlarından 0'a bölünenin yerinde "inf" yer tutucu ifadesi gelir.

C:\Users\user\AppData\Local\Temp/ipykernel_3720/1772489496.py:3: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr  # 1'i arrayin elemanlarına bölersek, hata değil uyarı alırız ve


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
# Numpy arraylerle pek çok aritmetik işlemler de yapabiliriz.
# Ör:

In [137]:
np.sqrt(arr)  # arrayin elemanlarının karekökünü almak için bu fonksiyon kullanılır.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [138]:
np.sin(arr)  # trigonometrik foksiyonlar da yapılabilir. Burada sinuslerini bulduk.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [139]:
np.log(arr)  # arraydeki elemanların log larını da alabiliriz.

C:\Users\user\AppData\Local\Temp/ipykernel_3720/1304882821.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)  # arraydeki elemanların log larını da alabiliriz.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Arraylerle yapılabilecek Basit İstatistiksel İşlemler

In [141]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
arr.sum()  # arrayin elemanlarının toplamını verir.

45

In [143]:
arr.mean()  # arrayin elemanlarını ortalamasını bulmak için kullanılır.

4.5

In [145]:
arr.max()  # array'in maks. elemanını bulmak için kullanılır.

9

In [146]:
arr.var()  # array'in varyansını bulmak için kullanılır.

8.25

In [ ]:
arr.std()  # array'in standart sapmasını (standart deviation) bulmak için kullanılır.

In [ ]:
# Tek boyutlu arraylerde elemanların toplamını yukarıdaki gibi bulabiliriz.
# Ancak İKİ BOYUTLU arrayler de toplamı bulmak için aşağıdaki yöntemi kullanmanız gerekir.


In [148]:
np.arange(0,25).reshape(5,5)  # Önce 25 elemanlı bir array oluşturduk, sonra da reshape ile iki boyutlu şekle dönüştürdük.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [149]:
arr2d = np.arange(0,25).reshape(5,5)

In [151]:
arr2d.shape

(5, 5)

In [152]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
arr2d.sum()  # Bu şekilde arrayin tüm elemanlarının toplamını bulabilirim.

300

In [ ]:
# Bütün kolonların ve bütün satırların toplamını bulmak istediğimde nasıl yapabilirim?

In [154]:
arr2d.sum(axis=0)  # axis=0 girildiğinde satırlar arasında toplama yaparak her bir kolonunun toplamlarını oluşturur.

array([50, 55, 60, 65, 70])

In [155]:
arr2d.sum(axis=1)  # axis = 1 girildiğinde ise kolonlar arasında toplama yaparak her bir satırın toplamını oluşturur.

array([ 10,  35,  60,  85, 110])